feat(take-a-break): Custom snooze time for take-a-break notification
johannesjo/super-productivity pull request #1228
Opened 2021-05-21 16:24 UTC by kwongtn

# Description

Default snooze value during being prompted for taking breaks after set N time is 15 mins.
This enhancement (hopefully) adds the function to allow users to define the snooze time.

## Issues Resolved

None that I know of

## Check List
Saw that testing was disabled, so did not write (I have yet to learn anyways 😝)
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable.

2021-05-21 20:01 UTC, johannesjo commented on src/assets/i18n/zh.json
> +      "SNOOZE_TIME": "[TRANSLATION REQUIRED] Snooze time when prompted to take a break",
It's best if you let those empty so my auto translate script can pick up on those.

2021-05-21 20:03 UTC, johannesjo commented
Hi there! That's a nice addition! Thank you very much! Just one thing: Could you remove those "[TRANSLATION REQUIRED] " strings? They would confuse my auto translate script :)

2021-05-22 01:09 UTC, kwongtn commented
Hi!
I've edited the commit accordingly 😁

2021-05-22 14:02 UTC, johannesjo requested changes

2021-05-22 14:02 UTC, johannesjo commented on src/app/features/time-tracking/take-a-break/take-a-break.service.ts
> +          fn: () => this.snooze(cfg.takeABreak.takeABreakSnoozeTime * 60 * 1000),
The `* 60 * 1000` won't work as intended. The duration field should be already in milliseconds.

2021-05-22 14:02 UTC, johannesjo commented on src/assets/i18n/es.json
> +      "SNOOZE_TIME": "",
```suggestion
```
This needs to be gone completley :)

2021-05-22 14:02 UTC, johannesjo commented on src/assets/i18n/fa.json
> +      "SNOOZE_TIME": "",
```suggestion
```

2021-05-22 16:15 UTC, kwongtn commented
I've edited the commits 😁 
Thank you very much for your patience with this 😥

2021-05-23 18:03 UTC, johannesjo commented
No Worries! Thank you very much for your work! :)

2021-05-23 18:03 UTC, merged